name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      #- name: Get yarn cache directory path
      #id: yarn-cache-dir-path
      #run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        #run: npm ci
        run:  yarn install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/.yarn-cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      #https://github.com/actions/cache/blob/main/examples.md#node---yarn
      #- name: Cache dependencies
        #uses: actions/cache@v3
        #with:
          #path: |
            #**/node_modules
        #key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
